// * 색상 변수
export const VAR_COLOR = {
	COLOR_PRIMARY: '#C92A2A',
	COLOR_SECONDARY: '#000',
	COLOR_TERTIARY: '#FFE9E9',
	COLOR_WHITE: '#fff',
	COLOR_BLACK: '#000',
	COLOR_LINE_GRAY: '#CACACA',
	COLOR_GRAY: '#E5E5E5'
};

// * 사이즈 변수
export const VAR_SIZE = {
	BASE_FONT_SIZE: 16,
	CONTENT_WIDTH: '1180px',
	HEADER_HEIGHT: '70px'
};

